#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use Dotenv\Environment\Adapter\EnvConstAdapter as V3EnvConstAdapter;
use Dotenv\Environment\Adapter\ServerConstAdapter as V3ServerConstAdapter;
use Dotenv\Environment\DotenvFactory;
use Dotenv\Repository\Adapter\EnvConstAdapter as V4orV5EnvConstAdapter;
use Dotenv\Repository\Adapter\ServerConstAdapter as V4orV5ServerConstAdapter;
use Dotenv\Repository\RepositoryBuilder;
use Illuminate\Container\Container;
use Composer\InstalledVersions;
use Ghostable\Application;
use Ghostable\Commands;

/**
 * Require the autoloader.
 */
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

/**
 * Load environment variables explicitly.
 */
(function () {
    if (class_exists(RepositoryBuilder::class)) {
        $adapters = [
            V4orV5EnvConstAdapter::class,
            V4orV5ServerConstAdapter::class,
        ];

        if (method_exists(RepositoryBuilder::class, 'addReader')) { // V5
            $repository = RepositoryBuilder::createWithNoAdapters();

            foreach ($adapters as $adapter) {
                $repository = $repository
                    ->addReader($adapter)
                    ->addWriter($adapter);
            }
        } else { // V4
            $adapters = array_map(fn ($adapterClass) => new $adapterClass(), $adapters);

            $repository = RepositoryBuilder::create()
                ->withReaders($adapters)
                ->withWriters($adapters);
        }

        Dotenv::create(
            $repository->immutable()->make(),
            getcwd()
        )->safeLoad();
    } else { // V3 fallback
        Dotenv::create(getcwd(), null, new DotenvFactory([
            new V3EnvConstAdapter, new V3ServerConstAdapter,
        ]))->safeLoad();
    }
})();

/**
 * Create the container instance.
 */
Container::setInstance($container = new Container);

/**
 * Start the console application.
 */
$version = InstalledVersions::getPrettyVersion('ghostable-dev/cli') ?? 'dev';
$app = new Application('Ghostable', $version);

// Authentication...
$app->add(new Commands\LoginCommand);

// Organizations...
$app->add(new Commands\OrganizationListCommand);
$app->add(new Commands\OrganizationCurrentCommand);
$app->add(new Commands\OrganizationSwitchCommand);

// Projects...
$app->add(new Commands\InitCommand);
$app->add(new Commands\ProjectListCommand);

// Environments...
$app->add(new Commands\EnvInitCommand);
$app->add(new Commands\EnvPushCommand);
$app->add(new Commands\EnvValidateCommand);
$app->add(new Commands\EnvDiffCommand);
$app->add(new Commands\EnvPullCommand);
$app->add(new Commands\EnvDeployCommand);
$app->add(new Commands\EnvForgeCommand);
$app->add(new Commands\EnvExportCommand);

// Secrets...
$app->add(new Commands\SecretListCommand);
$app->add(new Commands\SecretCreateCommand);
$app->add(new Commands\SecretUpdateCommand);
$app->add(new Commands\SecretWriteCommand);

$app->run();
