#!/usr/bin/env php
<?php

use Illuminate\Container\Container;
use Ghostable\Application;
use Ghostable\Commands;

/**
 * Require the autoloader.
 */
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

/**
 * Create the container instance.
 */
Container::setInstance($container = new Container);

/**
 * Start the console application.
 */
$app = new Application('Ghostable', '1.0.0');

// Authentication...
$app->add(new Commands\LoginCommand);

// Teams...
$app->add(new Commands\TeamListCommand);
$app->add(new Commands\TeamCurrentCommand);
$app->add(new Commands\TeamSwitchCommand);

// Projects ...
$app->add(new Commands\InitCommand);
$app->add(new Commands\ProjectListCommand);

// Environments
$app->add(new Commands\EnvInitCommand);
$app->add(new Commands\EnvPushCommand);
$app->add(new Commands\EnvPullCommand);
$app->add(new Commands\DeployCommand);

$app->run();