name: Lint & Auto-Format

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: ramsey/composer-install@v2
        with:
          composer-options: '--no-progress --no-interaction'
      - run: vendor/bin/pint
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: auto-format with Pint
          commit_options: '--no-verify'
          file_pattern: |
            **/*.php
            **/*.blade.php
            !.github/workflows/**
